import express from "express";
import * as authService from "../services/authService.js";

const router = express.Router();

// ── Doctor Auth ───────────────────────────────────────────────────────────────

/**
 * POST /auth/doctor/register
 * Body: { doctorID, fullName, licenseNumber, specialization, hospitalID, phone, email, password }
 * doctorID generated by idService before calling this — handled in doctorService
 */
router.post("/doctor/register", async (req, res) => {
    const { fullName, licenseNumber, specialization, hospitalID, phone, email, password, doctorID } = req.body;

    if (!fullName || !licenseNumber || !specialization || !hospitalID || !phone || !email || !password || !doctorID) {
        return res.status(400).json({ status: "FAILED", message: "All fields are required." });
    }

    const result = await authService.registerDoctor(req.body);
    return res.status(result.status === "SUCCESS" ? 200 : 400).json(result);
});

/**
 * POST /auth/doctor/login
 * Password-based login
 * Body: { phone, password }
 */
router.post("/doctor/login", async (req, res) => {
    const { phone, password } = req.body;

    if (!phone || !password) {
        return res.status(400).json({ status: "FAILED", message: "phone and password are required." });
    }

    const result = await authService.loginDoctorPassword(phone, password);
    return res.status(result.status === "SUCCESS" ? 200 : 401).json(result);
});

/**
 * POST /auth/doctor/otp/initiate
 * Body: { phone }
 */
router.post("/doctor/otp/initiate", async (req, res) => {
    const { phone } = req.body;

    if (!phone) {
        return res.status(400).json({ status: "FAILED", message: "phone is required." });
    }

    const result = await authService.initiateDoctorOTP(phone);
    return res.status(result.status === "OTP_SENT" ? 200 : 400).json(result);
});

/**
 * POST /auth/doctor/otp/verify
 * Body: { phone, otp }
 */
router.post("/doctor/otp/verify", async (req, res) => {
    const { phone, otp } = req.body;

    if (!phone || !otp) {
        return res.status(400).json({ status: "FAILED", message: "phone and otp are required." });
    }

    const result = await authService.verifyDoctorOTP(phone, otp);
    return res.status(result.status === "SUCCESS" ? 200 : 401).json(result);
});

// ── Patient Auth ──────────────────────────────────────────────────────────────

/**
 * POST /auth/patient/otp/initiate
 * Body: { phone }
 */
router.post("/patient/otp/initiate", async (req, res) => {
    const { phone } = req.body;

    if (!phone) {
        return res.status(400).json({ status: "FAILED", message: "phone is required." });
    }

    const result = await authService.initiatePatientOTP(phone);
    return res.status(result.status === "OTP_SENT" ? 200 : 400).json(result);
});

/**
 * POST /auth/patient/otp/verify
 * Body: { phone, otp }
 */
router.post("/patient/otp/verify", async (req, res) => {
    const { phone, otp } = req.body;

    if (!phone || !otp) {
        return res.status(400).json({ status: "FAILED", message: "phone and otp are required." });
    }

    const result = await authService.verifyPatientOTP(phone, otp);
    return res.status(result.status === "SUCCESS" ? 200 : 401).json(result);
});

export default router;
